// Test definitions. Do NOT edit this file!

#include <tuple>

#define CATCH_CONFIG_MAIN // defines main() automatically
#include "catch_amalgamated.hpp"

#include "student.hpp" // student implementations

// =====================
// tests for exercise 1
// ---------------------

TEST_CASE("Ex1", "[example]")
{
    REQUIRE(true);
}

// =====================
// tests for exercise 2
// ---------------------

TEST_CASE("Ex2", "[example]")
{
    REQUIRE(true);
}

